### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by gavinr** [kevinsagis/EnhancedLayerList#1]
I'm interested in what this widget does - but the demo site (http://sagiscloud.thempc.org/elayerlist/) does not seem to be working for me. Thanks!

**Comment by kevinsagis** [comment]
?Greetings Gavin,


The service that demo uses is on a server that's being upgraded over the next week or so and will be down during this time.


I have temporarily rerouted the demo app's webmap to another service. I randomly just grabbed a webmap for Georgia from some EPA viewer:
http://www.arcgis.com/home/item.html?id=9a33571d865e491bba8fff6c24d5a446


It had a Description entry. Remember, my widget grabs Description and CopyrightText from those fields on the REST service page, which are entered in the MXD that is published to create the service. If there are none it says No Information Available.

https://geodata.epa.gov/arcgis/rest/services/ORD/ROE_StateBoundaries/MapServer/0


So, I've updated it, you can check my demo page again. http://sagiscloud.thempc.org/elayerlist/


I actually just discovered with this change today, that images are supported in my metadata widget! Because it renders the inline html that is in the Description on the REST page. Awesome! I had not thought of leveraging that but I sure will be for my own apps from now on in the metadata boxes in my enhanced layer list widget for my own apps.  The EPA link to their metadata page is actually not configured or up at the moment but the image works and if their link was active it would link to a page on the metadat for their service.


[cid:131396a4-d97b-47a0-896d-8918580c73c9]


Best regards,

Kevin

SAGIS<http://www.sagis.org/>


________________________________

**Comment by gavinr** [comment]
Thanks a lot @kevinsagis!

**Comment by kevinsagis** [comment]
?Gavin I'd be interested to hear how you'll use my widget and see your site when you are done! Drop me a link if you'd like.


Best,

Kevin


________________________________
